# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(verbose_name='date published')),
                ('message', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('likes', models.IntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Person')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('published', models.DateTimeField(verbose_name='date published')),
                ('url', models.CharField(max_length=200)),
                ('likes', models.IntegerField(default=0)),
                ('retweet', models.IntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Person')),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='socialNetwork',
            new_name='idPost',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
