# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160323_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='idPost',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
